import os

# Scans / Tracking Tunables
TARGET_PCT = float(os.getenv("TARGET_PCT", "0.15"))
SL_PCT = float(os.getenv("SL_PCT", "0.05"))
TRAIL_SL_PCT = float(os.getenv("TRAIL_SL_PCT", "0.08"))
TRADE_ENTRY_MIN_SCORE = float(os.getenv("TRADE_ENTRY_MIN_SCORE", "70"))
REPORT_RETENTION_HOURS = int(os.getenv("REPORT_RETENTION_HOURS", "24"))

# Angel One Credentials
ANGEL_API_KEY = os.getenv("ANGEL_API_KEY", "6RRg3Xq0")
ANGEL_CLIENT_ID = os.getenv("ANGEL_CLIENT_ID", "U54894535")
ANGEL_PASSWORD = os.getenv("ANGEL_PASSWORD", "1609")
ANGEL_TOTP_KEY = os.getenv("ANGEL_TOTP_KEY", "LSTQSG4X7JFFOCDZY4XSCS653M")

# Telegram & Public Base URL Configs
APP_PUBLIC_BASE_URL = os.getenv("APP_PUBLIC_BASE_URL", "http://195.35.23.125:8023")

TELEGRAM_ENABLE_NEW_RUNNING_ALERTS = os.getenv(
    "TELEGRAM_ENABLE_NEW_RUNNING_ALERTS", "true"
).lower() in ("true", "1", "yes")

TELEGRAM_ENABLE_BOOKED_ALERTS = os.getenv(
    "TELEGRAM_ENABLE_BOOKED_ALERTS", "true"
).lower() in ("true", "1", "yes")

TELEGRAM_ENABLE_EOD_LINKS = os.getenv(
    "TELEGRAM_ENABLE_EOD_LINKS", "true"
).lower() in ("true", "1", "yes")

TELEGRAM_EOD_HOUR = int(os.getenv("TELEGRAM_EOD_HOUR", "15"))
TELEGRAM_EOD_MINUTE = int(os.getenv("TELEGRAM_EOD_MINUTE", "35"))

TELEGRAM_SEND_ENABLED = os.getenv("TELEGRAM_SEND_ENABLED", "true").lower() in ("true", "1", "yes")

SECTOR_PLANET = {
    "Pharma": "MER",
    "Media & Telecom": "MER",
    "IT": "SUN",
    "PSU": "SUN",
    "Banking & Finance": "JUP",
    "Realty": "MAR",
    "FMCG / Consumer": "VEN",
    "Auto / Consumer": "VEN",
    "Capital Goods": "RAH/SAT",
    "Metals": "RAH/SAT",
    "Power": "RAH/SAT",
    "Oil & Gas": "RAH/SAT"
}

STOCK_SECTOR = {
    "360ONE": "Banking & Finance",
    "3MINDIA": "Capital Goods",
    "AADHARHFC": "Capital Goods",
    "AARTI": "Capital Goods",
    "AARTIIND": "Capital Goods",
    "AAVAS": "Banking & Finance",
    "ABB": "Capital Goods",
    "ABBOTINDIA": "Pharma",
    "ABBOTT": "Pharma",
    "ABCAPITAL": "Banking & Finance",
    "ABDL": "Capital Goods",
    "ABFRL": "Capital Goods",
    "ABLBL": "Capital Goods",
    "ABREL": "Capital Goods",
    "ABSLAMC": "Capital Goods",
    "ACC": "Metals",
    "ACE": "Capital Goods",
    "ACMESOLAR": "Power",
    "ACUTAAS": "Capital Goods",
    "ADANIENSOL": "Power",
    "ADANIENT": "Capital Goods",
    "ADANIGREEN": "Power",
    "ADANIPORTS": "Capital Goods",
    "ADANIPOWER": "Power",
    "AEGISLOG": "Capital Goods",
    "AEGISVOPAK": "Capital Goods",
    "AFCONS": "Capital Goods",
    "AFFLE": "IT",
    "AIAENG": "Capital Goods",
    "AIIL": "Capital Goods",
    "AJANTPHARM": "Pharma",
    "ALKEM": "Pharma",
    "AMARARAJA": "Auto / Consumer",
    "AMBER": "Capital Goods",
    "AMBUJACEM": "Metals",
    "ANANDRATHI": "Capital Goods",
    "ANANTRAJ": "Realty",
    "ANGELONE": "Banking & Finance",
    "ANTHEM": "Capital Goods",
    "ANURAS": "Capital Goods",
    "APARINDS": "Capital Goods",
    "APLAPOLLO": "Metals",
    "APOLLOHOSP": "Pharma",
    "APOLLOTYRE": "Auto / Consumer",
    "APTUS": "Banking & Finance",
    "ARE&M": "Capital Goods",
    "ASAHIINDIA": "Capital Goods",
    "ASHOKLEY": "Capital Goods",
    "ASIANPAINT": "FMCG / Consumer",
    "ASTERDM": "Pharma",
    "ASTRAL": "Capital Goods",
    "ATGL": "Oil & Gas",
    "ATHERENERG": "Capital Goods",
    "ATUL": "Capital Goods",
    "AUBANK": "Banking & Finance",
    "AUROPHARMA": "Pharma",
    "AWL": "Capital Goods",
    "AXISBANK": "Banking & Finance",
    "BAJAJ-AUTO": "Auto / Consumer",
    "BAJAJFINSV": "Banking & Finance",
    "BAJAJHFL": "Capital Goods",
    "BAJAJHLDNG": "Banking & Finance",
    "BAJFINANCE": "Banking & Finance",
    "BALKRISIND": "Auto / Consumer",
    "BALRAMCHIN": "Capital Goods",
    "BANDHANBNK": "Banking & Finance",
    "BANKBARODA": "Banking & Finance",
    "BANKINDIA": "Banking & Finance",
    "BATAINDIA": "Capital Goods",
    "BAYERCROP": "Capital Goods",
    "BBTC": "Capital Goods",
    "BDL": "Capital Goods",
    "BEL": "PSU",
    "BELRISE": "Capital Goods",
    "BEML": "Capital Goods",
    "BERGEPAINT": "FMCG / Consumer",
    "BHARATFORG": "Metals",
    "BHARTIARTL": "Media & Telecom",
    "BHARTIHEXA": "Capital Goods",
    "BHEL": "PSU",
    "BIKAJI": "Capital Goods",
    "BIOCON": "Pharma",
    "BLS": "Capital Goods",
    "BLUEDART": "Capital Goods",
    "BLUEJET": "Capital Goods",
    "BLUESTARCO": "FMCG / Consumer",
    "BOSCHLTD": "Capital Goods",
    "BPCL": "PSU",
    "BRIGADE": "Realty",
    "BRITANNIA": "FMCG / Consumer",
    "BSE": "Banking & Finance",
    "BSOFT": "Capital Goods",
    "CAMS": "Banking & Finance",
    "CANBK": "Banking & Finance",
    "CANFINHOME": "Capital Goods",
    "CANHLIFE": "Capital Goods",
    "CAPLIPOINT": "Capital Goods",
    "CARBORUNIV": "Capital Goods",
    "CARTRADE": "Capital Goods",
    "CASTROLIND": "Oil & Gas",
    "CCL": "FMCG / Consumer",
    "CDSL": "Banking & Finance",
    "CEAT": "Auto / Consumer",
    "CEATLTD": "Capital Goods",
    "CEMPRO": "Capital Goods",
    "CENTRALBK": "Banking & Finance",
    "CESC": "Power",
    "CGCL": "Capital Goods",
    "CGPOWER": "Capital Goods",
    "CHALET": "Capital Goods",
    "CHAMBLFERT": "Capital Goods",
    "CHENNPETRO": "Oil & Gas",
    "CHOICEIN": "Capital Goods",
    "CHOLAFIN": "Banking & Finance",
    "CHOLAHLDNG": "Capital Goods",
    "CIEINDIA": "Capital Goods",
    "CIPLA": "Pharma",
    "CLEAN": "Capital Goods",
    "CMSINFO": "IT",
    "COALINDIA": "PSU",
    "COCHINSHIP": "Capital Goods",
    "COFORGE": "IT",
    "COHANCE": "Capital Goods",
    "COLPAL": "FMCG / Consumer",
    "CONCOR": "PSU",
    "CONCORDBIO": "Pharma",
    "COROMANDEL": "Capital Goods",
    "CPPLUS": "Capital Goods",
    "CRAFTSMAN": "Auto / Consumer",
    "CREDITACC": "Banking & Finance",
    "CRISIL": "Capital Goods",
    "CROMPTON": "FMCG / Consumer",
    "CUB": "Capital Goods",
    "CUMMINSIND": "Capital Goods",
    "CYIENT": "IT",
    "DABUR": "FMCG / Consumer",
    "DALBHARAT": "Metals",
    "DATAPATTNS": "Capital Goods",
    "DCBBANK": "Banking & Finance",
    "DCMSHRIRAM": "Capital Goods",
    "DEEPAKFERT": "Capital Goods",
    "DEEPAKNTR": "Capital Goods",
    "DELHIVERY": "Capital Goods",
    "DEVYANI": "Capital Goods",
    "DIVISLAB": "Pharma",
    "DIXON": "Capital Goods",
    "DLF": "Realty",
    "DMART": "FMCG / Consumer",
    "DOMS": "Capital Goods",
    "DRREDDY": "Pharma",
    "EASEMYTRIP": "FMCG / Consumer",
    "ECLERX": "IT",
    "EICHERMOT": "Auto / Consumer",
    "EIDPARRY": "Capital Goods",
    "EIHOTEL": "FMCG / Consumer",
    "ELECON": "Capital Goods",
    "ELGIEQUIP": "Capital Goods",
    "EMAMILTD": "FMCG / Consumer",
    "EMCURE": "Pharma",
    "EMMVEE": "Capital Goods",
    "ENDURANCE": "Capital Goods",
    "ENGINERSIN": "Capital Goods",
    "ENRIN": "Capital Goods",
    "EQUITASBNK": "Banking & Finance",
    "ERIS": "Capital Goods",
    "ESCORTS": "Auto / Consumer",
    "ETERNAL": "Capital Goods",
    "EXIDEIND": "Auto / Consumer",
    "FACT": "Capital Goods",
    "FEDERALBNK": "Banking & Finance",
    "FINCABLES": "Capital Goods",
    "FINEORG": "Capital Goods",
    "FIRSTCRY": "Capital Goods",
    "FIVESTAR": "Banking & Finance",
    "FLUOROCHEM": "Capital Goods",
    "FORCEMOT": "Capital Goods",
    "FORTIS": "Pharma",
    "FSL": "IT",
    "GABRIEL": "Capital Goods",
    "GAIL": "PSU",
    "GALAXYSURF": "Capital Goods",
    "GALLANTT": "Capital Goods",
    "GESHIP": "Capital Goods",
    "GICRE": "Capital Goods",
    "GILLETTE": "Capital Goods",
    "GLAND": "Pharma",
    "GLAXO": "Pharma",
    "GLENMARK": "Pharma",
    "GMDCLTD": "Capital Goods",
    "GMRAIRPORT": "Capital Goods",
    "GMRINFRA": "Capital Goods",
    "GODFRYPHLP": "Capital Goods",
    "GODIGIT": "Capital Goods",
    "GODREJCP": "FMCG / Consumer",
    "GODREJIND": "Capital Goods",
    "GODREJPROP": "Realty",
    "GPIL": "Capital Goods",
    "GRANULES": "Pharma",
    "GRAPHITE": "Capital Goods",
    "GRASIM": "Metals",
    "GRAVITA": "Metals",
    "GRINDWELL": "Capital Goods",
    "GROWW": "IT",
    "GRSE": "Capital Goods",
    "GSPL": "Oil & Gas",
    "GVT&D": "Capital Goods",
    "HAL": "PSU",
    "HAPPYMINDS": "IT",
    "HAVELLS": "FMCG / Consumer",
    "HBLENGINE": "Capital Goods",
    "HCLTECH": "IT",
    "HDBFS": "Capital Goods",
    "HDFCAMC": "Capital Goods",
    "HDFCBANK": "Banking & Finance",
    "HDFCLIFE": "Banking & Finance",
    "HEG": "Capital Goods",
    "HEROMOTOCO": "Auto / Consumer",
    "HEXT": "Capital Goods",
    "HFCL": "Capital Goods",
    "HINDALCO": "Metals",
    "HINDCOPPER": "PSU",
    "HINDPETRO": "Capital Goods",
    "HINDUNILVR": "FMCG / Consumer",
    "HINDZINC": "Capital Goods",
    "HOMEFIRST": "Banking & Finance",
    "HONASA": "Capital Goods",
    "HONAUT": "Capital Goods",
    "HSCL": "Capital Goods",
    "HUDCO": "PSU",
    "HYUNDAI": "Capital Goods",
    "ICICIAMC": "Banking & Finance",
    "ICICIBANK": "Banking & Finance",
    "ICICIGI": "Banking & Finance",
    "ICICIPRULI": "Banking & Finance",
    "IDBI": "Banking & Finance",
    "IDEA": "Media & Telecom",
    "IDFCFIRSTB": "Banking & Finance",
    "IEX": "Capital Goods",
    "IFCI": "Capital Goods",
    "IGIL": "Capital Goods",
    "IGL": "Oil & Gas",
    "IIFL": "Banking & Finance",
    "IKS": "Capital Goods",
    "INDGN": "Capital Goods",
    "INDHOTEL": "FMCG / Consumer",
    "INDIACEM": "Capital Goods",
    "INDIAMART": "IT",
    "INDIANB": "Banking & Finance",
    "INDIGO": "FMCG / Consumer",
    "INDUSINDBK": "Banking & Finance",
    "INDUSTOWER": "Media & Telecom",
    "INFY": "IT",
    "INOXWIND": "Capital Goods",
    "INTELLECT": "IT",
    "IOB": "Banking & Finance",
    "IOC": "PSU",
    "IPCA": "Pharma",
    "IPCALAB": "Pharma",
    "IRB": "Capital Goods",
    "IRCON": "PSU",
    "IRCTC": "FMCG / Consumer",
    "IREDA": "Capital Goods",
    "IRFC": "PSU",
    "ITC": "FMCG / Consumer",
    "ITCHOTELS": "Capital Goods",
    "ITI": "Capital Goods",
    "J&KBANK": "Banking & Finance",
    "JAINREC": "Capital Goods",
    "JBCHEPHARM": "Pharma",
    "JBMA": "Capital Goods",
    "JINDALSAW": "Metals",
    "JINDALSTEL": "Metals",
    "JIOFIN": "Capital Goods",
    "JKCEMENT": "Metals",
    "JKTYRE": "Capital Goods",
    "JMFINANCIL": "Banking & Finance",
    "JPPOWER": "Capital Goods",
    "JSL": "Metals",
    "JSWCEMENT": "Capital Goods",
    "JSWDULUX": "Capital Goods",
    "JSWENERGY": "Power",
    "JSWINFRA": "Capital Goods",
    "JSWSTEEL": "Metals",
    "JUBLFOOD": "Capital Goods",
    "JUBLINGREA": "Capital Goods",
    "JUBLPHARMA": "Pharma",
    "JUSTDIAL": "IT",
    "JWL": "Capital Goods",
    "JYOTHYLAB": "FMCG / Consumer",
    "JYOTICNC": "Capital Goods",
    "KAJARIACER": "Capital Goods",
    "KALYANKJIL": "Capital Goods",
    "KARURVYSYA": "Banking & Finance",
    "KAYNES": "Capital Goods",
    "KEC": "Capital Goods",
    "KEI": "Capital Goods",
    "KFINTECH": "Banking & Finance",
    "KIMS": "Capital Goods",
    "KIRLOSENG": "Capital Goods",
    "KOTAKBANK": "Banking & Finance",
    "KPIL": "Capital Goods",
    "KPITTECH": "IT",
    "KPRMILL": "Capital Goods",
    "KRBL": "FMCG / Consumer",
    "LALPATHLAB": "Pharma",
    "LATENTVIEW": "Capital Goods",
    "LAURUSLABS": "Pharma",
    "LEMONTREE": "Capital Goods",
    "LENSKART": "Capital Goods",
    "LGEINDIA": "Capital Goods",
    "LICHSGFIN": "Banking & Finance",
    "LICI": "Banking & Finance",
    "LINDEINDIA": "Capital Goods",
    "LLOYDSME": "Capital Goods",
    "LODHA": "Realty",
    "LT": "Capital Goods",
    "LTF": "Capital Goods",
    "LTFOODS": "FMCG / Consumer",
    "LTIM": "IT",
    "LTM": "Capital Goods",
    "LTTS": "IT",
    "LUPIN": "Pharma",
    "M&M": "Auto / Consumer",
    "M&MFIN": "Banking & Finance",
    "MAHABANK": "Capital Goods",
    "MAHINDCIE": "Auto / Consumer",
    "MAHLIFE": "Realty",
    "MAHLOG": "Capital Goods",
    "MANAPPURAM": "Banking & Finance",
    "MANKIND": "Pharma",
    "MAPMYINDIA": "IT",
    "MARICO": "FMCG / Consumer",
    "MARUTI": "Auto / Consumer",
    "MASTEK": "IT",
    "MAXHEALTH": "Pharma",
    "MAZDOCK": "Capital Goods",
    "MCDOWELL-N": "FMCG / Consumer",
    "MCX": "Banking & Finance",
    "MEDANTA": "Pharma",
    "MEESHO": "Capital Goods",
    "METROPOLIS": "Pharma",
    "MFSL": "Banking & Finance",
    "MGL": "Oil & Gas",
    "MINDACORP": "Capital Goods",
    "MMTC": "Capital Goods",
    "MOTHERSON": "Auto / Consumer",
    "MOTILALOFS": "Capital Goods",
    "MPHASIS": "IT",
    "MRF": "Auto / Consumer",
    "MRPL": "Oil & Gas",
    "MSUMI": "Capital Goods",
    "MUTHOOTFIN": "Banking & Finance",
    "NAM-INDIA": "Capital Goods",
    "NATCOPHARM": "Pharma",
    "NATIONALUM": "PSU",
    "NAUKRI": "IT",
    "NAVA": "Capital Goods",
    "NAVINFLUOR": "Capital Goods",
    "NBCC": "PSU",
    "NCC": "Capital Goods",
    "NESTLEIND": "FMCG / Consumer",
    "NETWEB": "Capital Goods",
    "NEULANDLAB": "Pharma",
    "NEWGEN": "IT",
    "NH": "Capital Goods",
    "NHPC": "PSU",
    "NIACL": "Capital Goods",
    "NIVABUPA": "Capital Goods",
    "NLCINDIA": "Capital Goods",
    "NMDC": "PSU",
    "NSLNISP": "Capital Goods",
    "NTPC": "PSU",
    "NTPCGREEN": "Capital Goods",
    "NUVAMA": "Capital Goods",
    "NUVOCO": "Metals",
    "NYKAA": "FMCG / Consumer",
    "OBEROIRLTY": "Realty",
    "OFSS": "Capital Goods",
    "OIL": "Oil & Gas",
    "OLAELEC": "Capital Goods",
    "OLECTRA": "Capital Goods",
    "ONESOURCE": "Capital Goods",
    "ONGC": "PSU",
    "PAGEIND": "FMCG / Consumer",
    "PARADEEP": "Capital Goods",
    "PATANJALI": "Capital Goods",
    "PAYTM": "IT",
    "PCBL": "Capital Goods",
    "PERSISTENT": "IT",
    "PETRONET": "Oil & Gas",
    "PFC": "PSU",
    "PFIZER": "Pharma",
    "PGEL": "Capital Goods",
    "PGHH": "FMCG / Consumer",
    "PHOENIXLTD": "Realty",
    "PIDILITIND": "Capital Goods",
    "PIIND": "Capital Goods",
    "PINELABS": "Capital Goods",
    "PIRAMALFIN": "Capital Goods",
    "PNB": "Banking & Finance",
    "PNBHOUSING": "Banking & Finance",
    "POLICYBZR": "IT",
    "POLYCAB": "Capital Goods",
    "POLYMED": "Capital Goods",
    "POONAWALLA": "Capital Goods",
    "POWERGRID": "PSU",
    "POWERINDIA": "Capital Goods",
    "PPLPHARMA": "Pharma",
    "PREMIERENE": "Power",
    "PRESTIGE": "Realty",
    "PTCIL": "Capital Goods",
    "PVRINOX": "Media & Telecom",
    "PWL": "Capital Goods",
    "RADICO": "FMCG / Consumer",
    "RAILTEL": "Capital Goods",
    "RAINBOW": "Pharma",
    "RAMCOCEM": "Metals",
    "RAMKRISHNA": "Metals",
    "RAYMOND": "FMCG / Consumer",
    "RBLBANK": "Banking & Finance",
    "RECLTD": "PSU",
    "REDINGTON": "Capital Goods",
    "RELIANCE": "Oil & Gas",
    "RHIM": "Capital Goods",
    "RITES": "Capital Goods",
    "RKFORGE": "Capital Goods",
    "ROUTE": "IT",
    "RPOWER": "Power",
    "RRKABEL": "Capital Goods",
    "RVNL": "PSU",
    "SAGILITY": "Pharma",
    "SAIL": "PSU",
    "SAILIFE": "Capital Goods",
    "SAMMAANCAP": "Banking & Finance",
    "SANOFI": "Pharma",
    "SAPPHIRE": "Capital Goods",
    "SARDAEN": "Capital Goods",
    "SAREGAMA": "Media & Telecom",
    "SBFC": "Banking & Finance",
    "SBICARD": "Capital Goods",
    "SBILIFE": "Banking & Finance",
    "SBIN": "Banking & Finance",
    "SCHAEFFLER": "Capital Goods",
    "SCHNEIDER": "Capital Goods",
    "SCI": "Capital Goods",
    "SHREECEM": "Metals",
    "SHRIRAMFIN": "Banking & Finance",
    "SHYAMMETL": "Metals",
    "SIEMENS": "Capital Goods",
    "SIGNATURE": "Realty",
    "SJVN": "PSU",
    "SOBHA": "Realty",
    "SOLARA": "Pharma",
    "SOLARINDS": "Capital Goods",
    "SOLUTIONSINF": "Capital Goods",
    "SONACOMS": "Capital Goods",
    "SONATSOFTW": "IT",
    "SPLPETRO": "Oil & Gas",
    "SRF": "Capital Goods",
    "STARHEALTH": "Capital Goods",
    "SUDARSCHEM": "Capital Goods",
    "SUMICHEM": "Capital Goods",
    "SUNDARMFIN": "Banking & Finance",
    "SUNPHARMA": "Pharma",
    "SUNTECK": "Realty",
    "SUNTV": "Media & Telecom",
    "SUPRAJIT": "Auto / Consumer",
    "SUPREMEIND": "Capital Goods",
    "SUZLON": "Power",
    "SWANCORP": "Capital Goods",
    "SWIGGY": "Capital Goods",
    "SYNGENE": "Pharma",
    "SYRMA": "Capital Goods",
    "TANLA": "IT",
    "TARIL": "Capital Goods",
    "TATACAP": "Banking & Finance",
    "TATACHEM": "Capital Goods",
    "TATACOMM": "Media & Telecom",
    "TATACONSUM": "FMCG / Consumer",
    "TATAELXSI": "IT",
    "TATAINVEST": "Banking & Finance",
    "TATAMOTORS": "Auto / Consumer",
    "TATAPOWER": "Power",
    "TATASTEEL": "Metals",
    "TATATECH": "IT",
    "TBOTEK": "Capital Goods",
    "TCI": "Capital Goods",
    "TCS": "IT",
    "TECHM": "IT",
    "TECHNOE": "Capital Goods",
    "TEGA": "Capital Goods",
    "TEJASNET": "Capital Goods",
    "TENNIND": "Capital Goods",
    "THELEELA": "Capital Goods",
    "THERMAX": "Capital Goods",
    "THYROCARE": "Pharma",
    "TIINDIA": "Capital Goods",
    "TIMKEN": "Capital Goods",
    "TITAGARH": "Capital Goods",
    "TITAN": "FMCG / Consumer",
    "TMCV": "Capital Goods",
    "TMPV": "Capital Goods",
    "TORNTPHARM": "Pharma",
    "TORNTPOWER": "Power",
    "TRAVELFOOD": "Capital Goods",
    "TRENT": "FMCG / Consumer",
    "TRIDENT": "Capital Goods",
    "TRITURBINE": "Capital Goods",
    "TTML": "Media & Telecom",
    "TVSMOTOR": "Capital Goods",
    "UBL": "FMCG / Consumer",
    "UCOBANK": "Banking & Finance",
    "UJJIVANSFB": "Banking & Finance",
    "ULTRACEMCO": "Metals",
    "UNIONBANK": "Banking & Finance",
    "UNITDSPR": "Capital Goods",
    "UNOMINDA": "Capital Goods",
    "UPL": "Capital Goods",
    "URBANCO": "Capital Goods",
    "USHAMART": "Metals",
    "UTIAMC": "Banking & Finance",
    "VBL": "Capital Goods",
    "VEDL": "Metals",
    "VIJAYA": "Capital Goods",
    "VINATIORGA": "Capital Goods",
    "VMM": "Capital Goods",
    "VOLTAS": "FMCG / Consumer",
    "VSTIND": "FMCG / Consumer",
    "VTL": "Capital Goods",
    "WAAREEENER": "Power",
    "WELCORP": "Metals",
    "WELSPUNLIV": "Capital Goods",
    "WHIRLPOOL": "FMCG / Consumer",
    "WIPRO": "IT",
    "WOCKPHARMA": "Pharma",
    "YESBANK": "Banking & Finance",
    "ZEEL": "Media & Telecom",
    "ZENSAR": "IT",
    "ZENSARTECH": "IT",
    "ZENTEC": "Capital Goods",
    "ZFCVINDIA": "Capital Goods",
    "ZOMATO": "IT",
    "ZYDUSLIFE": "Pharma",
    "ZYDUSWELL": "Capital Goods"
}
